package com.kevindeyne.tasker.config

enum class RealdataFaker(val list : List<String>) {
	
	INSTANCE(listOf("Exception thrown when creating table with SQLDataType.UUID in MySQL",
					"Incorrect handling of Oracle quoted string literals in plain SQL",
					"Improve DSLContext.batchStore() Javadoc, indicating that it does not execute MERGE / UPSERT semantics",
					"Trigger generated errors are not fetched through jOOQ's plain SQL API",
					"Result.formatJSON() does not correctly format array types",
					"Error in Record.compareTo(...) Javadoc",
					"NullPointerException in AbstractRecord.intern0()",
					"ClobBinding and BlobBinding don't correctly inline their bind values",
					"XMLDatabase doesn't work when dialect is not a SQLDialect.family()",
					"Typo in DSLContext.fetchCount() and error in DSLContext.fetchExists() Javadoc ",
					"Compilation error in generated code when both SchemaVersionProvider and CatalogVersionProvider are applied",
					"Invalid column index on Oracle stored procedure call when return type is converted to boolean and argument type is defaulted",
					"Add javax.xml.bind:jaxb-api dependency and avoid using the implementation",
					"Upgrade Scala 2.10 dependency to 2.10.7",
					"Add <serializablePojos/> to allow for POJOs not to be Serializable",
					"Add <serializableInterfaces/> to allow for interfaces not to be Serializable",
					"Add code generation configuration for comments",
					"jOOQ website CSS is broken on Android",
					"Add support for ResultMapper that allows for constructing custom Result types",
					"DDLDatabase reports DECIMAL(65535, 32767) for precision/scale-less decimals",
					"Generate equals(), hashCode(), and toString() on XJC generated classes ",
					"H2 MetaTable's string column default values are wrong",
					"Using VARBINARY type with length on Oracle fails in DDL statements",
					"NullPointerException when DSL.name(Name...) contains a null Name argument",
					"Services should only allow access from service loadbalancer source ranges - [k8s.io] Kubernetes e2e suite",
					"Ci-kubernetes-e2e-gci-gce-release-1.4: broken test run",
					"Federated ingress e2e test contains invalid spec: spec.ports[0].protocol: Invalid value: \"#\": cannot create an external load balancer with non-TCP/UDP ports",
					"Client certificate auth is using the subject CN from the intermediate CA cert, not from the end entity cert ",
					"Federated Ingress always routes to a single cluster with intermittent downtime.",
					"Compile darwin binaries with go 1.7.1 so they stop sefaulting",
					"Adding --runtime-config=\"api/all=false\" crashes apiserver",
					"Log rotate all /var/log log files in GCI",
					"How to pass MDC context from calling thread to timer thread in case of hystrix time out fallback",
					"Observable.flatMap() multiple executions when multiple subscribers",
					"java.lang.RuntimeException: unsubscribed before executing run() with request caching enabled",
					"Hystrix Circuit breaker: Increment hystrix metrics (intentionally)programmatically in custom code.",
					"related to Future fallback for Async Hystrix Command #929",
					"Update documentation on allowMaximumSizeToDivergeFromCoreSize",
					"Always download the gradle-4.0-all.zip when using the gradlew jettyRun for dashboard",
					"HystrixSampleSseServlet not sending data when ShallowEtagHeaderFilter is used"))
}