/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq.tables;


import com.kevindeyne.tasker.jooq.Indexes;
import com.kevindeyne.tasker.jooq.Keys;
import com.kevindeyne.tasker.jooq.Taskr;
import com.kevindeyne.tasker.jooq.tables.records.ProjectUsersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectUsers extends TableImpl<ProjectUsersRecord> {

    private static final long serialVersionUID = 51484692;

    /**
     * The reference instance of <code>taskr.project_users</code>
     */
    public static final ProjectUsers PROJECT_USERS = new ProjectUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectUsersRecord> getRecordType() {
        return ProjectUsersRecord.class;
    }

    /**
     * The column <code>taskr.project_users.id</code>.
     */
    public final TableField<ProjectUsersRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>taskr.project_users.project_id</code>.
     */
    public final TableField<ProjectUsersRecord, Long> PROJECT_ID = createField("project_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>taskr.project_users.user_id</code>.
     */
    public final TableField<ProjectUsersRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>taskr.project_users</code> table reference
     */
    public ProjectUsers() {
        this(DSL.name("project_users"), null);
    }

    /**
     * Create an aliased <code>taskr.project_users</code> table reference
     */
    public ProjectUsers(String alias) {
        this(DSL.name(alias), PROJECT_USERS);
    }

    /**
     * Create an aliased <code>taskr.project_users</code> table reference
     */
    public ProjectUsers(Name alias) {
        this(alias, PROJECT_USERS);
    }

    private ProjectUsers(Name alias, Table<ProjectUsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProjectUsers(Name alias, Table<ProjectUsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taskr.TASKR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PROJECT_USERS_PRIMARY, Indexes.PROJECT_USERS_PROJECT_ID, Indexes.PROJECT_USERS_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProjectUsersRecord, Long> getIdentity() {
        return Keys.IDENTITY_PROJECT_USERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProjectUsersRecord> getPrimaryKey() {
        return Keys.KEY_PROJECT_USERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProjectUsersRecord>> getKeys() {
        return Arrays.<UniqueKey<ProjectUsersRecord>>asList(Keys.KEY_PROJECT_USERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectUsers as(String alias) {
        return new ProjectUsers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectUsers as(Name alias) {
        return new ProjectUsers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectUsers rename(String name) {
        return new ProjectUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectUsers rename(Name name) {
        return new ProjectUsers(name, null);
    }
}
