/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq.tables;


import com.kevindeyne.tasker.jooq.Indexes;
import com.kevindeyne.tasker.jooq.Keys;
import com.kevindeyne.tasker.jooq.Taskr;
import com.kevindeyne.tasker.jooq.tables.records.ReleasesChangelogRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReleasesChangelog extends TableImpl<ReleasesChangelogRecord> {

    private static final long serialVersionUID = -458675009;

    /**
     * The reference instance of <code>taskr.releases_changelog</code>
     */
    public static final ReleasesChangelog RELEASES_CHANGELOG = new ReleasesChangelog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReleasesChangelogRecord> getRecordType() {
        return ReleasesChangelogRecord.class;
    }

    /**
     * The column <code>taskr.releases_changelog.id</code>.
     */
    public final TableField<ReleasesChangelogRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>taskr.releases_changelog.release_id</code>.
     */
    public final TableField<ReleasesChangelogRecord, Long> RELEASE_ID = createField("release_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>taskr.releases_changelog.issue_id</code>.
     */
    public final TableField<ReleasesChangelogRecord, Long> ISSUE_ID = createField("issue_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>taskr.releases_changelog</code> table reference
     */
    public ReleasesChangelog() {
        this(DSL.name("releases_changelog"), null);
    }

    /**
     * Create an aliased <code>taskr.releases_changelog</code> table reference
     */
    public ReleasesChangelog(String alias) {
        this(DSL.name(alias), RELEASES_CHANGELOG);
    }

    /**
     * Create an aliased <code>taskr.releases_changelog</code> table reference
     */
    public ReleasesChangelog(Name alias) {
        this(alias, RELEASES_CHANGELOG);
    }

    private ReleasesChangelog(Name alias, Table<ReleasesChangelogRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReleasesChangelog(Name alias, Table<ReleasesChangelogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taskr.TASKR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RELEASES_CHANGELOG_ISSUE_ID, Indexes.RELEASES_CHANGELOG_PRIMARY, Indexes.RELEASES_CHANGELOG_RELEASE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ReleasesChangelogRecord, Long> getIdentity() {
        return Keys.IDENTITY_RELEASES_CHANGELOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReleasesChangelogRecord> getPrimaryKey() {
        return Keys.KEY_RELEASES_CHANGELOG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReleasesChangelogRecord>> getKeys() {
        return Arrays.<UniqueKey<ReleasesChangelogRecord>>asList(Keys.KEY_RELEASES_CHANGELOG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ReleasesChangelogRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ReleasesChangelogRecord, ?>>asList(Keys.RELEASES_CHANGELOG_IBFK_2, Keys.RELEASES_CHANGELOG_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReleasesChangelog as(String alias) {
        return new ReleasesChangelog(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReleasesChangelog as(Name alias) {
        return new ReleasesChangelog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReleasesChangelog rename(String name) {
        return new ReleasesChangelog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReleasesChangelog rename(Name name) {
        return new ReleasesChangelog(name, null);
    }
}
