/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq.tables;


import com.kevindeyne.tasker.jooq.Indexes;
import com.kevindeyne.tasker.jooq.Keys;
import com.kevindeyne.tasker.jooq.Taskr;
import com.kevindeyne.tasker.jooq.tables.records.ReleasesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Releases extends TableImpl<ReleasesRecord> {

    private static final long serialVersionUID = -1273347101;

    /**
     * The reference instance of <code>taskr.releases</code>
     */
    public static final Releases RELEASES = new Releases();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReleasesRecord> getRecordType() {
        return ReleasesRecord.class;
    }

    /**
     * The column <code>taskr.releases.id</code>.
     */
    public final TableField<ReleasesRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>taskr.releases.version</code>.
     */
    public final TableField<ReleasesRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>taskr.releases.release_date</code>.
     */
    public final TableField<ReleasesRecord, Long> RELEASE_DATE = createField("release_date", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>taskr.releases</code> table reference
     */
    public Releases() {
        this(DSL.name("releases"), null);
    }

    /**
     * Create an aliased <code>taskr.releases</code> table reference
     */
    public Releases(String alias) {
        this(DSL.name(alias), RELEASES);
    }

    /**
     * Create an aliased <code>taskr.releases</code> table reference
     */
    public Releases(Name alias) {
        this(alias, RELEASES);
    }

    private Releases(Name alias, Table<ReleasesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Releases(Name alias, Table<ReleasesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taskr.TASKR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RELEASES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ReleasesRecord, Long> getIdentity() {
        return Keys.IDENTITY_RELEASES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReleasesRecord> getPrimaryKey() {
        return Keys.KEY_RELEASES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReleasesRecord>> getKeys() {
        return Arrays.<UniqueKey<ReleasesRecord>>asList(Keys.KEY_RELEASES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Releases as(String alias) {
        return new Releases(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Releases as(Name alias) {
        return new Releases(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Releases rename(String name) {
        return new Releases(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Releases rename(Name name) {
        return new Releases(name, null);
    }
}
