/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq.tables;


import com.kevindeyne.tasker.jooq.Indexes;
import com.kevindeyne.tasker.jooq.Keys;
import com.kevindeyne.tasker.jooq.Taskr;
import com.kevindeyne.tasker.jooq.tables.records.SprintRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sprint extends TableImpl<SprintRecord> {

    private static final long serialVersionUID = -1998886313;

    /**
     * The reference instance of <code>taskr.sprint</code>
     */
    public static final Sprint SPRINT = new Sprint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SprintRecord> getRecordType() {
        return SprintRecord.class;
    }

    /**
     * The column <code>taskr.sprint.id</code>.
     */
    public final TableField<SprintRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>taskr.sprint.start_date</code>.
     */
    public final TableField<SprintRecord, Timestamp> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>taskr.sprint.end_date</code>.
     */
    public final TableField<SprintRecord, Timestamp> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>taskr.sprint.project_id</code>.
     */
    public final TableField<SprintRecord, Long> PROJECT_ID = createField("project_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>taskr.sprint</code> table reference
     */
    public Sprint() {
        this(DSL.name("sprint"), null);
    }

    /**
     * Create an aliased <code>taskr.sprint</code> table reference
     */
    public Sprint(String alias) {
        this(DSL.name(alias), SPRINT);
    }

    /**
     * Create an aliased <code>taskr.sprint</code> table reference
     */
    public Sprint(Name alias) {
        this(alias, SPRINT);
    }

    private Sprint(Name alias, Table<SprintRecord> aliased) {
        this(alias, aliased, null);
    }

    private Sprint(Name alias, Table<SprintRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taskr.TASKR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SPRINT_PRIMARY, Indexes.SPRINT_PROJECT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SprintRecord, Long> getIdentity() {
        return Keys.IDENTITY_SPRINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SprintRecord> getPrimaryKey() {
        return Keys.KEY_SPRINT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SprintRecord>> getKeys() {
        return Arrays.<UniqueKey<SprintRecord>>asList(Keys.KEY_SPRINT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SprintRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SprintRecord, ?>>asList(Keys.SPRINT_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Sprint as(String alias) {
        return new Sprint(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Sprint as(Name alias) {
        return new Sprint(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sprint rename(String name) {
        return new Sprint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sprint rename(Name name) {
        return new Sprint(name, null);
    }
}
