/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq.tables;


import com.kevindeyne.tasker.jooq.Indexes;
import com.kevindeyne.tasker.jooq.Keys;
import com.kevindeyne.tasker.jooq.Taskr;
import com.kevindeyne.tasker.jooq.tables.records.TagcloudRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tagcloud extends TableImpl<TagcloudRecord> {

    private static final long serialVersionUID = -868866236;

    /**
     * The reference instance of <code>taskr.tagcloud</code>
     */
    public static final Tagcloud TAGCLOUD = new Tagcloud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagcloudRecord> getRecordType() {
        return TagcloudRecord.class;
    }

    /**
     * The column <code>taskr.tagcloud.id</code>.
     */
    public final TableField<TagcloudRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>taskr.tagcloud.issue_id</code>.
     */
    public final TableField<TagcloudRecord, Long> ISSUE_ID = createField("issue_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>taskr.tagcloud.tag_id</code>.
     */
    public final TableField<TagcloudRecord, Long> TAG_ID = createField("tag_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>taskr.tagcloud</code> table reference
     */
    public Tagcloud() {
        this(DSL.name("tagcloud"), null);
    }

    /**
     * Create an aliased <code>taskr.tagcloud</code> table reference
     */
    public Tagcloud(String alias) {
        this(DSL.name(alias), TAGCLOUD);
    }

    /**
     * Create an aliased <code>taskr.tagcloud</code> table reference
     */
    public Tagcloud(Name alias) {
        this(alias, TAGCLOUD);
    }

    private Tagcloud(Name alias, Table<TagcloudRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tagcloud(Name alias, Table<TagcloudRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taskr.TASKR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAGCLOUD_ISSUE_ID, Indexes.TAGCLOUD_PRIMARY, Indexes.TAGCLOUD_TAG_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TagcloudRecord, Long> getIdentity() {
        return Keys.IDENTITY_TAGCLOUD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TagcloudRecord> getPrimaryKey() {
        return Keys.KEY_TAGCLOUD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TagcloudRecord>> getKeys() {
        return Arrays.<UniqueKey<TagcloudRecord>>asList(Keys.KEY_TAGCLOUD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TagcloudRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TagcloudRecord, ?>>asList(Keys.TAGCLOUD_IBFK_1, Keys.TAGCLOUD_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tagcloud as(String alias) {
        return new Tagcloud(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tagcloud as(Name alias) {
        return new Tagcloud(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tagcloud rename(String name) {
        return new Tagcloud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tagcloud rename(Name name) {
        return new Tagcloud(name, null);
    }
}
