/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq.tables;


import com.kevindeyne.tasker.jooq.Indexes;
import com.kevindeyne.tasker.jooq.Keys;
import com.kevindeyne.tasker.jooq.Taskr;
import com.kevindeyne.tasker.jooq.tables.records.VersionIssueRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VersionIssue extends TableImpl<VersionIssueRecord> {

    private static final long serialVersionUID = -1148972847;

    /**
     * The reference instance of <code>taskr.version_issue</code>
     */
    public static final VersionIssue VERSION_ISSUE = new VersionIssue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VersionIssueRecord> getRecordType() {
        return VersionIssueRecord.class;
    }

    /**
     * The column <code>taskr.version_issue.id</code>.
     */
    public final TableField<VersionIssueRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>taskr.version_issue.versions_id</code>.
     */
    public final TableField<VersionIssueRecord, Long> VERSIONS_ID = createField("versions_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>taskr.version_issue.issue_id</code>.
     */
    public final TableField<VersionIssueRecord, Long> ISSUE_ID = createField("issue_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>taskr.version_issue</code> table reference
     */
    public VersionIssue() {
        this(DSL.name("version_issue"), null);
    }

    /**
     * Create an aliased <code>taskr.version_issue</code> table reference
     */
    public VersionIssue(String alias) {
        this(DSL.name(alias), VERSION_ISSUE);
    }

    /**
     * Create an aliased <code>taskr.version_issue</code> table reference
     */
    public VersionIssue(Name alias) {
        this(alias, VERSION_ISSUE);
    }

    private VersionIssue(Name alias, Table<VersionIssueRecord> aliased) {
        this(alias, aliased, null);
    }

    private VersionIssue(Name alias, Table<VersionIssueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Taskr.TASKR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.VERSION_ISSUE_ISSUE_ID, Indexes.VERSION_ISSUE_PRIMARY, Indexes.VERSION_ISSUE_VERSIONS_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<VersionIssueRecord, Long> getIdentity() {
        return Keys.IDENTITY_VERSION_ISSUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VersionIssueRecord> getPrimaryKey() {
        return Keys.KEY_VERSION_ISSUE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VersionIssueRecord>> getKeys() {
        return Arrays.<UniqueKey<VersionIssueRecord>>asList(Keys.KEY_VERSION_ISSUE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VersionIssueRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VersionIssueRecord, ?>>asList(Keys.VERSION_ISSUE_IBFK_1, Keys.VERSION_ISSUE_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionIssue as(String alias) {
        return new VersionIssue(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionIssue as(Name alias) {
        return new VersionIssue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VersionIssue rename(String name) {
        return new VersionIssue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VersionIssue rename(Name name) {
        return new VersionIssue(name, null);
    }
}
