/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq;


import com.kevindeyne.tasker.jooq.tables.Event;
import com.kevindeyne.tasker.jooq.tables.Issue;
import com.kevindeyne.tasker.jooq.tables.SchemaVersion;
import com.kevindeyne.tasker.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in taskr
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>taskr.event</code>.
     */
    public static final Event EVENT = com.kevindeyne.tasker.jooq.tables.Event.EVENT;

    /**
     * The table <code>taskr.issue</code>.
     */
    public static final Issue ISSUE = com.kevindeyne.tasker.jooq.tables.Issue.ISSUE;

    /**
     * The table <code>taskr.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = com.kevindeyne.tasker.jooq.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>taskr.user</code>.
     */
    public static final User USER = com.kevindeyne.tasker.jooq.tables.User.USER;
}
