/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq;


import com.kevindeyne.tasker.jooq.tables.Event;
import com.kevindeyne.tasker.jooq.tables.InProgress;
import com.kevindeyne.tasker.jooq.tables.Issue;
import com.kevindeyne.tasker.jooq.tables.Knowledge;
import com.kevindeyne.tasker.jooq.tables.Project;
import com.kevindeyne.tasker.jooq.tables.ProjectUsers;
import com.kevindeyne.tasker.jooq.tables.SchemaVersion;
import com.kevindeyne.tasker.jooq.tables.Sprint;
import com.kevindeyne.tasker.jooq.tables.Tag;
import com.kevindeyne.tasker.jooq.tables.Tagcloud;
import com.kevindeyne.tasker.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taskr extends SchemaImpl {

    private static final long serialVersionUID = 1713251187;

    /**
     * The reference instance of <code>taskr</code>
     */
    public static final Taskr TASKR = new Taskr();

    /**
     * The table <code>taskr.event</code>.
     */
    public final Event EVENT = com.kevindeyne.tasker.jooq.tables.Event.EVENT;

    /**
     * The table <code>taskr.in_progress</code>.
     */
    public final InProgress IN_PROGRESS = com.kevindeyne.tasker.jooq.tables.InProgress.IN_PROGRESS;

    /**
     * The table <code>taskr.issue</code>.
     */
    public final Issue ISSUE = com.kevindeyne.tasker.jooq.tables.Issue.ISSUE;

    /**
     * The table <code>taskr.knowledge</code>.
     */
    public final Knowledge KNOWLEDGE = com.kevindeyne.tasker.jooq.tables.Knowledge.KNOWLEDGE;

    /**
     * The table <code>taskr.project</code>.
     */
    public final Project PROJECT = com.kevindeyne.tasker.jooq.tables.Project.PROJECT;

    /**
     * The table <code>taskr.project_users</code>.
     */
    public final ProjectUsers PROJECT_USERS = com.kevindeyne.tasker.jooq.tables.ProjectUsers.PROJECT_USERS;

    /**
     * The table <code>taskr.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = com.kevindeyne.tasker.jooq.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>taskr.sprint</code>.
     */
    public final Sprint SPRINT = com.kevindeyne.tasker.jooq.tables.Sprint.SPRINT;

    /**
     * The table <code>taskr.tag</code>.
     */
    public final Tag TAG = com.kevindeyne.tasker.jooq.tables.Tag.TAG;

    /**
     * The table <code>taskr.tagcloud</code>.
     */
    public final Tagcloud TAGCLOUD = com.kevindeyne.tasker.jooq.tables.Tagcloud.TAGCLOUD;

    /**
     * The table <code>taskr.user</code>.
     */
    public final User USER = com.kevindeyne.tasker.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Taskr() {
        super("taskr", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Event.EVENT,
            InProgress.IN_PROGRESS,
            Issue.ISSUE,
            Knowledge.KNOWLEDGE,
            Project.PROJECT,
            ProjectUsers.PROJECT_USERS,
            SchemaVersion.SCHEMA_VERSION,
            Sprint.SPRINT,
            Tag.TAG,
            Tagcloud.TAGCLOUD,
            User.USER);
    }
}
