/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq;


import com.kevindeyne.tasker.jooq.tables.Branch;
import com.kevindeyne.tasker.jooq.tables.Comments;
import com.kevindeyne.tasker.jooq.tables.Event;
import com.kevindeyne.tasker.jooq.tables.FlywaySchemaHistory;
import com.kevindeyne.tasker.jooq.tables.Invitation;
import com.kevindeyne.tasker.jooq.tables.Issue;
import com.kevindeyne.tasker.jooq.tables.Knowledge;
import com.kevindeyne.tasker.jooq.tables.Project;
import com.kevindeyne.tasker.jooq.tables.ProjectUsers;
import com.kevindeyne.tasker.jooq.tables.Releases;
import com.kevindeyne.tasker.jooq.tables.ReleasesChangelog;
import com.kevindeyne.tasker.jooq.tables.Search;
import com.kevindeyne.tasker.jooq.tables.Sprint;
import com.kevindeyne.tasker.jooq.tables.Tag;
import com.kevindeyne.tasker.jooq.tables.Tagcloud;
import com.kevindeyne.tasker.jooq.tables.Timesheet;
import com.kevindeyne.tasker.jooq.tables.User;
import com.kevindeyne.tasker.jooq.tables.UserRole;
import com.kevindeyne.tasker.jooq.tables.VersionIssue;
import com.kevindeyne.tasker.jooq.tables.Versions;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taskr extends SchemaImpl {

    private static final long serialVersionUID = 1174911278;

    /**
     * The reference instance of <code>taskr</code>
     */
    public static final Taskr TASKR = new Taskr();

    /**
     * The table <code>taskr.branch</code>.
     */
    public final Branch BRANCH = com.kevindeyne.tasker.jooq.tables.Branch.BRANCH;

    /**
     * The table <code>taskr.comments</code>.
     */
    public final Comments COMMENTS = com.kevindeyne.tasker.jooq.tables.Comments.COMMENTS;

    /**
     * The table <code>taskr.event</code>.
     */
    public final Event EVENT = com.kevindeyne.tasker.jooq.tables.Event.EVENT;

    /**
     * The table <code>taskr.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.kevindeyne.tasker.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>taskr.invitation</code>.
     */
    public final Invitation INVITATION = com.kevindeyne.tasker.jooq.tables.Invitation.INVITATION;

    /**
     * The table <code>taskr.issue</code>.
     */
    public final Issue ISSUE = com.kevindeyne.tasker.jooq.tables.Issue.ISSUE;

    /**
     * The table <code>taskr.knowledge</code>.
     */
    public final Knowledge KNOWLEDGE = com.kevindeyne.tasker.jooq.tables.Knowledge.KNOWLEDGE;

    /**
     * The table <code>taskr.project</code>.
     */
    public final Project PROJECT = com.kevindeyne.tasker.jooq.tables.Project.PROJECT;

    /**
     * The table <code>taskr.project_users</code>.
     */
    public final ProjectUsers PROJECT_USERS = com.kevindeyne.tasker.jooq.tables.ProjectUsers.PROJECT_USERS;

    /**
     * The table <code>taskr.releases</code>.
     */
    public final Releases RELEASES = com.kevindeyne.tasker.jooq.tables.Releases.RELEASES;

    /**
     * The table <code>taskr.releases_changelog</code>.
     */
    public final ReleasesChangelog RELEASES_CHANGELOG = com.kevindeyne.tasker.jooq.tables.ReleasesChangelog.RELEASES_CHANGELOG;

    /**
     * The table <code>taskr.search</code>.
     */
    public final Search SEARCH = com.kevindeyne.tasker.jooq.tables.Search.SEARCH;

    /**
     * The table <code>taskr.sprint</code>.
     */
    public final Sprint SPRINT = com.kevindeyne.tasker.jooq.tables.Sprint.SPRINT;

    /**
     * The table <code>taskr.tag</code>.
     */
    public final Tag TAG = com.kevindeyne.tasker.jooq.tables.Tag.TAG;

    /**
     * The table <code>taskr.tagcloud</code>.
     */
    public final Tagcloud TAGCLOUD = com.kevindeyne.tasker.jooq.tables.Tagcloud.TAGCLOUD;

    /**
     * The table <code>taskr.timesheet</code>.
     */
    public final Timesheet TIMESHEET = com.kevindeyne.tasker.jooq.tables.Timesheet.TIMESHEET;

    /**
     * The table <code>taskr.user</code>.
     */
    public final User USER = com.kevindeyne.tasker.jooq.tables.User.USER;

    /**
     * The table <code>taskr.user_role</code>.
     */
    public final UserRole USER_ROLE = com.kevindeyne.tasker.jooq.tables.UserRole.USER_ROLE;

    /**
     * The table <code>taskr.versions</code>.
     */
    public final Versions VERSIONS = com.kevindeyne.tasker.jooq.tables.Versions.VERSIONS;

    /**
     * The table <code>taskr.version_issue</code>.
     */
    public final VersionIssue VERSION_ISSUE = com.kevindeyne.tasker.jooq.tables.VersionIssue.VERSION_ISSUE;

    /**
     * No further instances allowed
     */
    private Taskr() {
        super("taskr", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Branch.BRANCH,
            Comments.COMMENTS,
            Event.EVENT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Invitation.INVITATION,
            Issue.ISSUE,
            Knowledge.KNOWLEDGE,
            Project.PROJECT,
            ProjectUsers.PROJECT_USERS,
            Releases.RELEASES,
            ReleasesChangelog.RELEASES_CHANGELOG,
            Search.SEARCH,
            Sprint.SPRINT,
            Tag.TAG,
            Tagcloud.TAGCLOUD,
            Timesheet.TIMESHEET,
            User.USER,
            UserRole.USER_ROLE,
            Versions.VERSIONS,
            VersionIssue.VERSION_ISSUE);
    }
}
