/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq.tables.records;


import com.kevindeyne.tasker.jooq.tables.Sprint;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SprintRecord extends UpdatableRecordImpl<SprintRecord> implements Record4<Long, Timestamp, Timestamp, Long> {

    private static final long serialVersionUID = 153621931;

    /**
     * Setter for <code>taskr.sprint.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>taskr.sprint.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>taskr.sprint.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>taskr.sprint.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>taskr.sprint.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>taskr.sprint.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>taskr.sprint.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>taskr.sprint.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Timestamp, Timestamp, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Timestamp, Timestamp, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Sprint.SPRINT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Sprint.SPRINT.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Sprint.SPRINT.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Sprint.SPRINT.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord value2(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord value3(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord value4(Long value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord values(Long value1, Timestamp value2, Timestamp value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SprintRecord
     */
    public SprintRecord() {
        super(Sprint.SPRINT);
    }

    /**
     * Create a detached, initialised SprintRecord
     */
    public SprintRecord(Long id, Timestamp startDate, Timestamp endDate, Long projectId) {
        super(Sprint.SPRINT);

        set(0, id);
        set(1, startDate);
        set(2, endDate);
        set(3, projectId);
    }
}
