/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq.tables.records;


import com.kevindeyne.tasker.jooq.tables.Sprint;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SprintRecord extends UpdatableRecordImpl<SprintRecord> implements Record6<Long, Timestamp, Timestamp, Long, Integer, Integer> {

    private static final long serialVersionUID = -1500908107;

    /**
     * Setter for <code>taskr.sprint.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>taskr.sprint.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>taskr.sprint.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>taskr.sprint.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>taskr.sprint.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>taskr.sprint.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>taskr.sprint.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>taskr.sprint.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>taskr.sprint.backlog_at_start</code>.
     */
    public void setBacklogAtStart(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>taskr.sprint.backlog_at_start</code>.
     */
    public Integer getBacklogAtStart() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>taskr.sprint.sprint_nr</code>.
     */
    public void setSprintNr(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>taskr.sprint.sprint_nr</code>.
     */
    public Integer getSprintNr() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Timestamp, Timestamp, Long, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Timestamp, Timestamp, Long, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Sprint.SPRINT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Sprint.SPRINT.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Sprint.SPRINT.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Sprint.SPRINT.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Sprint.SPRINT.BACKLOG_AT_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Sprint.SPRINT.SPRINT_NR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getBacklogAtStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getSprintNr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getBacklogAtStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSprintNr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord value2(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord value3(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord value4(Long value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord value5(Integer value) {
        setBacklogAtStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord value6(Integer value) {
        setSprintNr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintRecord values(Long value1, Timestamp value2, Timestamp value3, Long value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SprintRecord
     */
    public SprintRecord() {
        super(Sprint.SPRINT);
    }

    /**
     * Create a detached, initialised SprintRecord
     */
    public SprintRecord(Long id, Timestamp startDate, Timestamp endDate, Long projectId, Integer backlogAtStart, Integer sprintNr) {
        super(Sprint.SPRINT);

        set(0, id);
        set(1, startDate);
        set(2, endDate);
        set(3, projectId);
        set(4, backlogAtStart);
        set(5, sprintNr);
    }
}
