/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq.tables.records;


import com.kevindeyne.tasker.jooq.tables.Tagcloud;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagcloudRecord extends UpdatableRecordImpl<TagcloudRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = -1557624992;

    /**
     * Setter for <code>taskr.tagcloud.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>taskr.tagcloud.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>taskr.tagcloud.issue_id</code>.
     */
    public void setIssueId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>taskr.tagcloud.issue_id</code>.
     */
    public Long getIssueId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>taskr.tagcloud.tag_id</code>.
     */
    public void setTagId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>taskr.tagcloud.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Tagcloud.TAGCLOUD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Tagcloud.TAGCLOUD.ISSUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Tagcloud.TAGCLOUD.TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getIssueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getIssueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagcloudRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagcloudRecord value2(Long value) {
        setIssueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagcloudRecord value3(Long value) {
        setTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagcloudRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagcloudRecord
     */
    public TagcloudRecord() {
        super(Tagcloud.TAGCLOUD);
    }

    /**
     * Create a detached, initialised TagcloudRecord
     */
    public TagcloudRecord(Long id, Long issueId, Long tagId) {
        super(Tagcloud.TAGCLOUD);

        set(0, id);
        set(1, issueId);
        set(2, tagId);
    }
}
