/*
 * This file is generated by jOOQ.
*/
package com.kevindeyne.tasker.jooq.tables.records;


import com.kevindeyne.tasker.jooq.tables.Timesheet;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimesheetRecord extends UpdatableRecordImpl<TimesheetRecord> implements Record6<Long, Timestamp, Timestamp, Integer, Long, Long> {

    private static final long serialVersionUID = 921217309;

    /**
     * Setter for <code>taskr.timesheet.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>taskr.timesheet.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>taskr.timesheet.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>taskr.timesheet.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>taskr.timesheet.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>taskr.timesheet.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>taskr.timesheet.avg_workday</code>.
     */
    public void setAvgWorkday(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>taskr.timesheet.avg_workday</code>.
     */
    public Integer getAvgWorkday() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>taskr.timesheet.issue_id</code>.
     */
    public void setIssueId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>taskr.timesheet.issue_id</code>.
     */
    public Long getIssueId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>taskr.timesheet.user_id</code>.
     */
    public void setUserId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>taskr.timesheet.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Timestamp, Timestamp, Integer, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Timestamp, Timestamp, Integer, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Timesheet.TIMESHEET.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Timesheet.TIMESHEET.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Timesheet.TIMESHEET.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Timesheet.TIMESHEET.AVG_WORKDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Timesheet.TIMESHEET.ISSUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Timesheet.TIMESHEET.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAvgWorkday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getIssueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAvgWorkday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getIssueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimesheetRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimesheetRecord value2(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimesheetRecord value3(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimesheetRecord value4(Integer value) {
        setAvgWorkday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimesheetRecord value5(Long value) {
        setIssueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimesheetRecord value6(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimesheetRecord values(Long value1, Timestamp value2, Timestamp value3, Integer value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TimesheetRecord
     */
    public TimesheetRecord() {
        super(Timesheet.TIMESHEET);
    }

    /**
     * Create a detached, initialised TimesheetRecord
     */
    public TimesheetRecord(Long id, Timestamp startDate, Timestamp endDate, Integer avgWorkday, Long issueId, Long userId) {
        super(Timesheet.TIMESHEET);

        set(0, id);
        set(1, startDate);
        set(2, endDate);
        set(3, avgWorkday);
        set(4, issueId);
        set(5, userId);
    }
}
