package com.kevindeyne.tasker.amq

enum class AMQMessageType {
	
	ISSUE_CREATE_OR_EDIT,
	ISSUE_PROGRESS,
	ISSUE_IMPACT,
	ISSUE_URGENCY,
	ISSUE_ASSIGNEE,
	ISSUE_FIXVERSION,
	ISSUE_ADD_VERSION,
	ISSUE_REMOVE_VERSION
	
}